config/routes.rb
AbcrowdComposers::Application.routes.draw do
  
  devise_for :users

  # Change this?
  root :to => 'subjects#index'

  resources :subjects, only: [:index, :create, :destroy]

  resources :topics, only: [:show, :destroy]

  get 'subject/:id/topics' => 'topics#index', as: 'topics'

  post 'subject/:id/topics' => 'topics#create' #, as: 'create_topic'
  
  resources :lyrics, only: [:show, :create, :update]
  

  get 'topics/:id/lyrics/new' => 'lyrics#new', as: "new_topic_lyrics"

  resources :lyric_versions, only: [:show, :create, :update]

  post 'lyric_versions/:id/like' => 'lyric_versions#like', as: 'like_lyric_version'
  post 'lyric_version/showjs' => 'lyric_versions#showjs', as: 'get_lyric_version'

  post 'lines/:id/cancel' => 'lines#cancel', as: 'cancel_edit_line'
  get 'lines/:id' => 'lines#new', as: 'new_line'
  put 'lines/:id' => 'lines#update', as: 'lyric_line'
  post 'lines/' => 'lines#create', as: 'lyric_lines'

  get 'lines/:id/insert_line' => 'lines#insert_line', as: 'insert_line'
  get 'lines/:id/next' => 'lines#next_line', as: 'next_line'
  get 'lines/:id/previous' => 'lines#previous_line', as: 'previous_line'

  get 'audio_snippets' => 'audio_snippets#index', as: 'audio_snippets'

end
#== Route Map
# Generated on 25 Sep 2013 18:39
#
#             user_session POST   /users/sign_in(.:format)         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
#            user_password POST   /users/password(.:format)        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#                          PUT    /users/password(.:format)        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)          devise/registrations#cancel
#        user_registration POST   /users(.:format)                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)            devise/registrations#edit
#                          PUT    /users(.:format)                 devise/registrations#update
#                          DELETE /users(.:format)                 devise/registrations#destroy
#                     root        /                                subjects#index
#                 subjects GET    /subjects(.:format)              subjects#index
#                          POST   /subjects(.:format)              subjects#create
#                  subject DELETE /subjects/:id(.:format)          subjects#destroy
#                    topic GET    /topics/:id(.:format)            topics#show
#                          DELETE /topics/:id(.:format)            topics#destroy
#                   topics GET    /subject/:id/topics(.:format)    topics#index
#                          POST   /subject/:id/topics(.:format)    topics#create
#                   lyrics POST   /lyrics(.:format)                lyrics#create
#                    lyric GET    /lyrics/:id(.:format)            lyrics#show
#                          PUT    /lyrics/:id(.:format)            lyrics#update
#         new_topic_lyrics GET    /topics/:id/lyrics/new(.:format) lyrics#new
#           lyric_versions POST   /lyric_versions(.:format)        lyric_versions#create
#            lyric_version GET    /lyric_versions/:id(.:format)    lyric_versions#show
#                          PUT    /lyric_versions/:id(.:format)    lyric_versions#update
#                 new_line GET    /lines/:id(.:format)             lines#new
#               lyric_line PUT    /lines/:id(.:format)             lines#create
#                          POST   /lines/:id(.:format)             lines#create
#                next_line GET    /lines/:id/next(.:format)        lines#next_line
#            previous_line GET    /lines/:id/previous(.:format)    lines#previous_line

app/controllers/lines_controller.rb
class LinesController < ApplicationController
	#before_filter :authenticate_user!
	
	include LyricFun


	def new
		lyric_line = LyricLine.find params[:id]

		dump_form lyric_line
	end 

	# User changes an existing line
	def update
		old_lyric = LyricLine.find params[:id]
		text = params[:lyric_line][:text]
		p text
		if text.length < 1 || text == old_lyric.text || !/\w/.match(text)
			# don't save, add line back
			@placeholder = 'please enter a line'
			dump_line old_lyric	
		else
			lyric_line = LyricLine.new params[:lyric_line]
			lyric_line.version_number = get_next_version( lyric_line )
			lyric_line.save
			@first = params[:first]
			dump_line lyric_line
		end
	end

	# User 
	def create
		text = params[:lyric_line][:text]
		p params
		if text.length < 1 || !/\w/.match(text)
			# don't save
			@order_number = params[:lyric_line][:order_number]
			render 'cancel'
		else
			lyric_line = LyricLine.new params[:lyric_line]

			lyric_line.version_number = get_next_version( lyric_line )

			lyric_line.save

			@first = params[:first]

			dump_line lyric_line 
		end
	end

	# user changes mind and cancels the changes
	def cancel
		if params[:id] != 'new'
			lyric_line = LyricLine.find params[:id]
			dump_line lyric_line
		else
			@order_number = params[:order_number]
		end
	end

	# user clicks [insert line] button hits this controller
	def insert_line
		@first = params[:placement]['first'].to_f
		@second = params[:placement]['second'].to_f
		@new_order_number = @first + ( @second - @first ) / 2
		@lyric_id = params[:lyric_id]
		@lyric_line = LyricLine.new lyric_id: @lyric_id, order_number: @new_order_number
		@new = true
	end

	def next_line

		current_line = LyricLine.find params[:id]
		sql = "lyric_id = #{current_line.lyric_id} 
					 and order_number = #{current_line.order_number} 
					 and version_number = #{current_line.version_number + 1}"
		next_line = LyricLine.where(sql).first

		if next_line
			dump_line next_line
		else
			dump_form current_line
		end
	end

	def previous_line
		current_line = LyricLine.find params[:id]
		sql = "lyric_id = #{current_line.lyric_id} 
					 and order_number = #{current_line.order_number} 
					 and version_number = #{current_line.version_number - 1}"
		previous_line = LyricLine.where(sql).first

		if previous_line			
			dump_line previous_line
		else
			dump_form current_line
		end
	end

	private

		def dump_line(lyric_line)
			@lyric_line = lyric_line

			respond_to do |format|
				format.html { redirect_to request.referer }
				format.js { render 'update' }
			end
		end

		def dump_form(lyric_line)
			@lyric_line = lyric_line

			respond_to do |format|
				format.html { redirect_to request.referer }
				format.js { render 'new' }
			end
		end

end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_line_form.html.erb
<%= form_for lyric_line, remote: true do |f| %>
<%= f.text_field :text, placeholder: @placeholder || 'enter new lyric' %>
<%= f.hidden_field :order_number, value: lyric_line.order_number  %>
<%= f.hidden_field :lyric_id, value: lyric_line.lyric_id  %>

<% if @first %>
	<%= hidden_field_tag :first, @first %>
<% end %>
	<small class="not-a-button">
	<%= f.submit '[save edit]' %>
	</small>
<% end %>

<%= form_tag cancel_edit_line_path( lyric_line.id || 'new' ), remote: true do %>

<%= hidden_field_tag :order_number, lyric_line.order_number %>


<small class="not-a-button">

	<%= submit_tag '[cancel]' %>
	
</small>

<% end %>

app/views/lines/_line_link.html.erb
<h6>
<%= link_to line.text, new_line_path( line ), id: "link-#{line.order_number.to_i}" , remote: true %>
</h6>

app/views/lines/_test.html.erb
<p>this is a test</p>

app/views/lines/cancel.js.erb
var order_number = '<%= @order_number.to_i %>'
// var first = '<%= @first.to_i %>'
// var first_val = '<%= @first %>'

$('#entity-' + order_number).remove()
$('#form-hidden-' + order_number).remove()

console.log(order_number)

app/views/lines/create.js.erb
//replace text 

$('#line-<%= @lyric_line.order_number.to_i %>').html("<%= @lyric_line.text %>");
$('#next-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= next_line_path( @lyric_line ) %>");
$('#previous-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= previous_line_path( @lyric_line ) %>");
$('#form-hidden-<%= @lyric_line.order_number.to_i %>').attr("value", "<%= @lyric_line.id %>" )


$('#like').css({
	visibility: 'hidden'
});

$('#new-version').css({
	visibility: 'visible'
});

app/views/lines/insert_line.js.erb
var first = '<%= @first.to_i %>'
var first_val = '<%= @first %>'
var new_order_number = '<%= @new_order_number %>'
var line_entity = '<%= escape_javascript( render partial: "shared/line", locals: { line: @lyric_line } ) %>'


$('#entity-' + first).after(line_entity)
//$('#form-' + first + " .second").attr('value', new_order_number);
$('#form-hidden-' + first).after('<%= escape_javascript( hidden_field_tag "lyric_lines[]", "", id: "form-hidden-#{@lyric_line.order_number.to_i}" )%>')

app/views/lines/new.js.erb
//replace lyric with new box

$('#line-<%= @lyric_line.order_number.to_i %>').html("<%= escape_javascript( render( partial: 'lines/line_form', locals: { lyric_line: @lyric_line } ) ) %>")

app/views/lines/next_line.js.erb
//refactored to 'create'

$('#line-<%= @lyric_line.order_number.to_i %>').html("<%= @lyric_line.text %>")
$('#next-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= next_line_path( @lyric_line ) %>")
$('#previous-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= previous_line_path( @lyric_line ) %>")

app/views/lines/previous_line.js.erb
// refactored to 'create'

$('#line-<%= @lyric_line.order_number.to_i %>').html("<%= @lyric_line.text %>")
$('#next-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= next_line_path( @lyric_line ) %>")
$('#previous-<%= @lyric_line.order_number.to_i %>').attr("href", "<%= previous_line_path( @lyric_line ) %>")

app/views/lines/test.js.erb
console.log('hit re pattern')

app/views/lines/update.js.erb
//replace text 

var order_number = '<%= @lyric_line.order_number.to_i %>'
var line_link = "<%= escape_javascript(render partial: 'lines/line_link', locals: { line: @lyric_line }) %>"

$('#line-' + order_number).html(line_link);
$('#next-' + order_number).attr("href", "<%= next_line_path( @lyric_line ) %>");
$('#previous-' + order_number).attr("href", "<%= previous_line_path( @lyric_line ) %>");
$('#form-hidden-' + order_number).attr("value", "<%= @lyric_line.id %>" )


$('#like').css({
	visibility: 'hidden'
});

$('#new-version').css({
	visibility: 'visible'
});

<% if @first %>

var first = '<%= @first.to_i %>'

$('#form-' + first + " .second").attr('value', order_number);

console.log('edit data for first = ' + first)

<% end %>

// console.log(line_link)