config/routes.rb
AbcrowdComposers::Application.routes.draw do
  
  devise_for :users

  # Change this?
  root :to => 'subjects#index'

  resources :subjects, only: [:index, :create, :destroy]

  resources :topics, only: [:show, :destroy]

  get 'subject/:id/topics' => 'topics#index', as: 'topics'

  post 'subject/:id/topics' => 'topics#create' #, as: 'create_topic'
  
  resources :lyrics, only: [:show, :create, :update]
  

  get 'topics/:id/lyrics/new' => 'lyrics#new', as: "new_topic_lyrics"

  resources :lyric_versions, only: [:show, :create, :update]

  post 'lyric_versions/:id/like' => 'lyric_versions#like', as: 'like_lyric_version'
  post 'lyric_version/showjs' => 'lyric_versions#showjs', as: 'get_lyric_version'

  post 'lines/:id/cancel' => 'lines#cancel', as: 'cancel_edit_line'
  get 'lines/:id' => 'lines#new', as: 'new_line'
  put 'lines/:id' => 'lines#update', as: 'lyric_line'
  post 'lines/' => 'lines#create', as: 'lyric_lines'

  get 'lines/:id/insert_line' => 'lines#insert_line', as: 'insert_line'
  get 'lines/:id/next' => 'lines#next_line', as: 'next_line'
  get 'lines/:id/previous' => 'lines#previous_line', as: 'previous_line'

  get 'audio_snippets' => 'audio_snippets#index', as: 'audio_snippets'

end
#== Route Map
# Generated on 25 Sep 2013 18:39
#
#             user_session POST   /users/sign_in(.:format)         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
#            user_password POST   /users/password(.:format)        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#                          PUT    /users/password(.:format)        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)          devise/registrations#cancel
#        user_registration POST   /users(.:format)                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)            devise/registrations#edit
#                          PUT    /users(.:format)                 devise/registrations#update
#                          DELETE /users(.:format)                 devise/registrations#destroy
#                     root        /                                subjects#index
#                 subjects GET    /subjects(.:format)              subjects#index
#                          POST   /subjects(.:format)              subjects#create
#                  subject DELETE /subjects/:id(.:format)          subjects#destroy
#                    topic GET    /topics/:id(.:format)            topics#show
#                          DELETE /topics/:id(.:format)            topics#destroy
#                   topics GET    /subject/:id/topics(.:format)    topics#index
#                          POST   /subject/:id/topics(.:format)    topics#create
#                   lyrics POST   /lyrics(.:format)                lyrics#create
#                    lyric GET    /lyrics/:id(.:format)            lyrics#show
#                          PUT    /lyrics/:id(.:format)            lyrics#update
#         new_topic_lyrics GET    /topics/:id/lyrics/new(.:format) lyrics#new
#           lyric_versions POST   /lyric_versions(.:format)        lyric_versions#create
#            lyric_version GET    /lyric_versions/:id(.:format)    lyric_versions#show
#                          PUT    /lyric_versions/:id(.:format)    lyric_versions#update
#                 new_line GET    /lines/:id(.:format)             lines#new
#               lyric_line PUT    /lines/:id(.:format)             lines#create
#                          POST   /lines/:id(.:format)             lines#create
#                next_line GET    /lines/:id/next(.:format)        lines#next_line
#            previous_line GET    /lines/:id/previous(.:format)    lines#previous_line

app/views/shared/_insert_form.html.erb
<form action="<%= insert_line_path 10 %>" data-remote="true">

<%= hidden_field_tag "lyric_id", line.lyric_id %>

<%= hidden_field_tag "placement[first]", first  %>
<%= hidden_field_tag "placement[second]", second, class: 'second'  %>
	<small class="not-a-button">
		<%= submit_tag '--[insert line]--' %>
	</small>

</form>

app/views/shared/_line.html.erb
<div id="entity-<%= line.order_number.to_i %>" >

	<div class="one column alpha">
		<!-- PREVIOUS: previous-order_number -->
		<% if @new %>
			<%= link_to "", "#", 
					id: "previous-#{line.order_number.to_i}", 
					remote: true,
					class: 'icon-arrow-left'  %>
		<% else %>
			<%= link_to "", previous_line_path( line ), 
					id: "previous-#{line.order_number.to_i}", 
					remote: true,
					class: 'icon-arrow-left'  %>
		<% end %>
	</div>
	
	<!-- LINE: line-order_number -->
	<div class="six columns" id="line-<%= line.order_number.to_i %>" >
		<% if @new %>
			<%= render partial: 'lines/line_form',
					   locals: { lyric_line: line } %>
		<% else %>
			<%= render partial: 'lines/line_link', 
					   locals: { line: line } %>
		<% end %>
	</div>

	<div class="one column omega">
		<!-- NEXT: next-order_number -->
		<% if @new %>
			<%= link_to "", "#", 
					id: "next-#{line.order_number.to_i}" , 
					remote: true,
					class: 'icon-arrow-right' %>
		<% else %>
			<%= link_to "", next_line_path( line ), 
					id: "next-#{line.order_number.to_i}" , 
					remote: true,
					class: 'icon-arrow-right' %>
		<% end %>

	</div>

	<br class="clear">

	<div class="offset-by-one six columns alpha omega insert-link" >

		<div id="form-<%= line.order_number.to_i %>">

		<!-- insert form -->
		<%= render partial: 'shared/insert_form',
				   locals: { line: line,
				   			 first: line.order_number,
				   			 second: @second || get_second_line( lyric_lines, line ) } %>
		</div>

	</div>

	<br class="clear">

</div>

app/views/shared/_line_entity.html.erb
<div class="row entity-<%= line.order_number %>" >

<div class="one column">

	<%= link_to "<<", previous_line_path( line ), 
				id: "previous-#{line.order_number.to_i}", 
				remote: true  %>

</div>

<div class="six columns" id="line-<%= line.order_number.to_i %>" >

	<%= render partial: 'lines/line_link', 
			   locals: { line: line } %>

</div>

<div class="one column">

	<%= link_to ">>", next_line_path( line ), 
				id: "next-#{line.order_number.to_i}" , 
				remote: true %>

</div>

<br class="clear">
<div class="offset-by-two four columns insert-link" >

<form id="order-<%= line.order_number.to_i %>" action="<%= insert_line_path line %>" data-remote="true">

<%= hidden_field_tag "lyric_id", line.lyric_id %>

<%= hidden_field_tag "placement[first]", line.order_number  %>
<%= hidden_field_tag "placement[second]", get_second_line( lyric_lines, line )  %>
	<small>
		<%= submit_tag '[insert line]' %>
	</small>

</form>
</div>

</div>


<br class="clear">

app/views/shared/_lyric_line_form_vals.html.erb
<% lyric_lines.each do |line| %>

<%= hidden_field_tag 'lyric_lines[]', line.id, id: "form-hidden-#{line.order_number.to_i}" %>

<% end %>

app/views/shared/_lyric_lines.html.erb
<div id="entity-0" >


<div class="offset-by-one six columns alpha omega insert-link" >
	<div id="form-0">

	<!-- insert form -->
	<%= render partial: 'shared/insert_form',
			   locals: { line: lyric_lines.first,
			   			 first: 0,
			   			 second: lyric_lines.first.order_number } %>

	</div>
</div>

<br class="clear">


</div>


<% lyric_lines.each do |line| %>
	<%= render partial: 'shared/line', 
			   locals: { line: line, lyric_lines: lyric_lines } %>
<% end %>

app/views/shared/_lyric_version.html.erb
<div class="offset-by-one eight columns">
	<h3><%= link_to @lyric_version.title, lyric_version_path( @lyric_version ) %></h3>
</div>
<div class="offset-by-one eight columns">
<%= render partial: 'shared/lyric_lines', 
		   locals: { lyric_lines: @lyric_lines } %>
</div>

<div class= 'six columns'>
	<%= render partial: 'shared/version_likes', locals: { lyric_version: @lyric_version } %>
</div>

<div id="new-version" style="visibility: hidden;" class="six columns">
	<h3>You started a new version!</h3>
	<%= form_tag lyric_versions_path do %>
		<%= hidden_field_tag 'lyric_id', @lyric_version.lyric_id %>

		<%= render partial: 'shared/lyric_line_form_vals', locals: { lyric_lines: @lyric_lines } %>
		<small class="not-a-button">
			<%= submit_tag '[save it]' %>
		</small>
	<% end %>
</div>

<br class="clear">






<div class="offset-by-one eight columns">
	<div class="six columns alpha add-bottom">
		<%= link_to '[Submit Audio for this Lyric]', audio_snippets_path %>
	</div>

	<div class="six columns alpha double-bottom">
		<%= link_to '[New Lyric]', new_topic_lyrics_path( @lyric.topic_id ) %>
	</div>
</div>

app/views/shared/_lyric_versions_select.html.erb
<%= form_tag get_lyric_version_path, remote: true do %>

<%= select_tag :lyric_version, options_for_select(@versions_for_select) %>

<small class="not-a-button insert-link">
	<%= submit_tag '[go]' %>
</small> 

<% end %>

app/views/shared/_version_likes.html.erb
<div id="like">

	<h2>likes: <span id="likes-count"><%= lyric_version.likes %></span></h2>
	<small class="not-a-button">
		<%= button_to '[Like this!]', like_lyric_version_path( lyric_version ), remote: true %>	
	</small>
</div>